### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by hyyaoming** [SusionSuc/DraggableViewer#2]
老哥能提供一个java版嘛？

**Comment by SusionSuc** [comment]
这个恐怕有点难。。。。  java版本-> kotlin还可以。。。。。

**Comment by hyyaoming** [comment]
我可以提个PR弄个java版嘛，好东西得让更多人用起来。

**Comment by hyyaoming** [comment]
目前我改的java版地址在这里https://github.com/hyyaoming/BasisProject/tree/master/dragimageview
