### ISSUE TITLE
方法showImages()传入false依然显示下载按钮

### ISSUE THREAD

**Issue by q88qaz** [SusionSuc/DraggableViewer#4]
方法：  fun showImages(
        context: Context,
        images: List<String>,
        index: Int = 0,
        showDownLoadBtn: Boolean = true
    )

 ImageViewerHelper.INSTANCE.showImages(BaseActivity.getForegroundActivity(), imageList, position, false);
传入false依然显示下载按钮

**Comment by SusionSuc** [comment]
v1.0.2 fixed
